app/destinations/forms.py
import pycountry
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileRequired
from wtforms import (BooleanField, DecimalField, FileField, HiddenField,
                     IntegerField, MultipleFileField, SelectField, StringField,
                     SubmitField, TextAreaField)
from wtforms.validators import DataRequired, Optional, ValidationError, Email

from app import images
from app.models import Destination


class DestinationSelectField(SelectField):
    def __init__(self, *args, **kwargs):
        super(DestinationSelectField, self).__init__(*args, **kwargs)
        destinations = Destination.query.all()
        self.choices = [(d.title, d.title) for d in destinations]
        self.choices.insert(0, ('', 'Choose Destination'))


class suggestUpdateForm(FlaskForm):
    subject = StringField('Subject', validators=[DataRequired()])
    destination_title = DestinationSelectField('Destination to update', validators=[DataRequired()])
    sender_email = StringField('Email', validators=[DataRequired(), Email()])
    message = TextAreaField('Message', validators=[DataRequired()])
    submit = SubmitField('Send')


class CountrySelectField(SelectField):
    def __init__(self, *args, **kwargs):
        super(CountrySelectField, self).__init__(*args, **kwargs)
        self.choices = [(country.alpha_2, country.name) for country in pycountry.countries]
        self.choices.insert(0, ('', 'Choose Country'))


class DestinationForm(FlaskForm):
    # General information
    title = StringField('Name of destination', render_kw={"placeholder": "e.g. 'Kalymnos'"}, validators=[DataRequired()])
    country = CountrySelectField('Country', validators=[DataRequired()])
    weather_place_autocomplete = StringField('Place to use for weather forecast ', validators=[DataRequired()])
    weather_ltd = HiddenField('Latitude', validators=[DataRequired()])
    weather_lng = HiddenField('Longitude', validators=[DataRequired()])
    featured_photo = FileField('Featured Photo', validators=[FileRequired(), FileAllowed(images, 'JPG/JPEG images only!')])
    additional_photos = MultipleFileField('Additional Photos', validators=[FileAllowed(images, 'Images only!')])
    description = TextAreaField('Description')

    # Disciplines
    traditional = BooleanField('Traditional')
    sport = BooleanField('Sport')
    bouldering = BooleanField('Bouldering')
    main_discipline = SelectField('Main discipline',
                                  choices=[('traditional', 'Traditional'),
                                           ('bouldering', 'Bouldering'),
                                           ('sport', 'Sport')],
                                  validators=[DataRequired()])

    # Months/Season
    january = BooleanField('January')
    february = BooleanField('February')
    march = BooleanField('March')
    april = BooleanField('April')
    may = BooleanField('May')
    june = BooleanField('June')
    july = BooleanField('July')
    august = BooleanField('August')
    september = BooleanField('September')
    october = BooleanField('October')
    november = BooleanField('November')
    december = BooleanField('December')

    # Accomodation
    tent = BooleanField('Tent')
    van = BooleanField('Van')
    hostel = BooleanField('Hostel')
    camping = BooleanField('Camping')
    apartment = BooleanField('Apartment')
    house = BooleanField('House')
    hotel = BooleanField('Hotel')

    # Approach
    easy = BooleanField('Easy')
    moderate = BooleanField('Moderate')
    hardcore = BooleanField('Hardcore')

    # Car
    not_needed = BooleanField('Not needed')
    good_to_have = BooleanField('Good to have')
    must_have = BooleanField('Must have')
    rent_scooter_locally = BooleanField('Scooter available locally')
    rent_car_locally = BooleanField('Car available locally')

    # Cost
    cost_form_currency = SelectField('Currency',
                                     choices=[('EUR', 'EUR'), ('AUD', 'AUD'), ('BGN', 'BGN'),
                                              ('BRL', 'BRL'), ('CAD', 'CAD'), ('CHF', 'CHF'),
                                              ('CNY', 'CNY'), ('CZK', 'CZK'), ('DKK', 'DKK'),
                                              ('GBP', 'GBP'), ('HKD', 'HKD'), ('HRK', 'HRK'),
                                              ('HUF', 'HUF'), ('IDR', 'IDR'), ('ILS', 'ILS'),
                                              ('INR', 'INR'), ('ISK', 'ISK'), ('JPY', 'JPY'),
                                              ('KRW', 'KRW'), ('MXN', 'MXN'), ('MYR', 'MYR'),
                                              ('NOK', 'NOK'), ('NZD', 'NZD'), ('PHP', 'PHP'),
                                              ('PLN', 'PLN'), ('RON', 'RON'), ('RUB', 'RUB'),
                                              ('SEK', 'SEK'), ('SGD', 'SGD'), ('THB', 'THB'),
                                              ('TRY', 'TRY'), ('USD', 'USD'), ('ZAR', 'ZAR')],
                                     validators=[DataRequired()],
                                     default='EUR')
    beer_at_establishment = DecimalField('Beer at establishment', render_kw={"placeholder": "e.g. '2.5'", "class": "integer"}, validators=[DataRequired()])
    coffee_at_establishment = DecimalField('Coffee at establishment', render_kw={"class": "integer"}, validators=[DataRequired()])
    restaurant_inexpensive_meal = DecimalField('Inexpensive meal at restaurant', render_kw={"class": "integer"}, validators=[DataRequired()])
    groceries_one_week = DecimalField('One week of groceries', render_kw={"class": "integer"}, validators=[DataRequired()])
    car_rent_one_week = DecimalField('One week car rental', render_kw={"placeholder": "e.g. '143'", "class": "integer"}, validators=[Optional()])
    gas_one_liter = DecimalField('One liter of gas', render_kw={"class": "integer"}, validators=[Optional()])
    km_per_day = DecimalField('Average kilometers of driving per day', render_kw={"class": "integer"}, validators=[Optional()])
    tent_per_day = DecimalField('Tent (per night)', render_kw={"placeholder": "e.g. '9'", "class": "integer"}, validators=[Optional()])
    van_per_day = DecimalField('Van (per night)', render_kw={"class": "integer"}, validators=[Optional()])
    camping_per_day = DecimalField('Camping (per night)', render_kw={"class": "integer"}, validators=[Optional()])
    hostel_per_day = DecimalField('Hostel (per night)', render_kw={"class": "integer"}, validators=[Optional()])
    apartment_per_day = DecimalField('Apartment (per night)', render_kw={"class": "integer"}, validators=[Optional()])
    house_per_day = DecimalField('House (per night)', render_kw={"class": "integer"}, validators=[Optional()])
    hotel_per_day = DecimalField('Hotel (per night)', render_kw={"class": "integer"}, validators=[Optional()])

    # Routes
    total_routes = IntegerField('Total number of routes (including sport, trad and boulder problems)', render_kw={"placeholder": "e.g. '1250'", "class": "integer"}, validators=[Optional()])
    total_sport = IntegerField('Number of sport routes', render_kw={"class": "integer"}, validators=[Optional()])
    total_trad = IntegerField('Number of traditional routes', render_kw={"class": "integer"}, validators=[Optional()])
    total_boulders = IntegerField('Number of boulder problems', render_kw={"class": "integer"}, validators=[Optional()])
    easy_routes = DecimalField('Number of easy routes (up to 4+)', render_kw={"class": "integer"}, validators=[Optional()])
    intermediate_routes = DecimalField('Number of intermediate routes (5 to 6a+)', render_kw={"class": "integer"}, validators=[Optional()])
    hard_routes = DecimalField('Number of hard routes (6b to 7a)', render_kw={"class": "integer"}, validators=[Optional()])
    very_hard_routes = DecimalField('Number of hard routes (7a+ and up)', render_kw={"class": "integer"}, validators=[Optional()])

    # Submit
    submit = SubmitField('Add Destination!')

    def validate_title(self, title):  # When you add any methods that match the pattern validate_<field_name>,
                                            # WTForms takes those as custom validators and invokes them in addition to
                                            # the stock validators. In this case I want to make sure that the username
                                            # and email address entered by the user are not already in the database, so
                                            # these two methods issue database queries expecting there will be no
                                            # results. In the event a result exists, a validation error is triggered
                                            # by raising ValidationError. The message included as the argument in the
                                            # exception will be the message that will be displayed next to the field
                                            # for the user to see.
        destination = Destination.query.filter_by(title=title.data).first()
        if destination is not None:
            raise ValidationError('This name is already in use. If you want to add information to an existing destination, please email me at eric.m.thorn@gmail.com, or use the feedback forum.')


class EditDestinationForm(FlaskForm):
    # General information
    title = StringField('Name of destination', render_kw={"placeholder": "e.g. 'Kalymnos'"}, validators=[DataRequired()])
    country = CountrySelectField('Country')
    weather_place_autocomplete = StringField('Place to use for weather forecast ')
    weather_ltd = HiddenField('Latitude', validators=[DataRequired()])
    weather_lng = HiddenField('Longitude', validators=[DataRequired()])
    featured_photo = FileField('Featured Photo', validators=[FileAllowed(images, 'JPG/JPEG images only!')])
    additional_photos = MultipleFileField('Additional Photos', validators=[FileAllowed(images, 'Images only!')])
    description = TextAreaField('Description')

    # Disciplines

app/destinations/__init__.py
from flask import Blueprint

bp = Blueprint('destinations', __name__)

from app.destinations import routes

app/destinations/routes.py
import pycountry_convert
from flask import flash, redirect, render_template, request, url_for
from flask_login import login_required

from app import db
from app.destinations import bp
from app.destinations.email import send_suggest_update_email
from app.destinations.forms import (DestinationForm, EditDestinationForm,
                                    suggestUpdateForm)
from app.destinations.save_destination import save_destination
from app.models import AdditionalPhotos, Destination


@bp.route('/suggest_update/', methods=['GET', 'POST'])
@bp.route('/suggest_update/<int:id>', methods=['GET', 'POST'])
def suggest_update(id=None):
    form = suggestUpdateForm()

    destination = Destination.query.get(id)

    if form.validate_on_submit():
        subject = form.subject.data
        sender_email = form.sender_email.data
        destination_title = form.destination_title.data
        message = form.message.data

        send_suggest_update_email(subject, sender_email, destination_title, message)
        
        flash('The message has been sent!')
        return redirect(url_for('main.single', id=id))

    return render_template('destinations/suggest_update.html',
                           title='Suggest update',
                           form=form,
                           destination=destination)


@bp.route('/add_destination', methods=['GET', 'POST'])
@login_required
def add_destination():
    # Cannot pass in 'request.form' to AddRecipeForm constructor, as this will cause 'request.files' to not be
    # sent to the form.  This will cause AddRecipeForm to not see the file data.
    # Flask-WTF handles passing form data to the form, so not parameters need to be included.
    def flash_errors(form):
        for field, errors in form.errors.items():
            for error in errors:
                flash(u"Error in the %s field - %s" % (
                    getattr(form, field).label.text,
                    error
                ))

    form = DestinationForm()
    if request.method == 'POST':  # image upload
        if form.validate_on_submit():
            if save_destination(form, new=True):
                flash('Destination "{}" added!'.format(str(form.title.data)))
                return redirect(url_for('main.index'))
        else:
            flash_errors(form)
            flash('ERROR! Destination was not added.', 'error')
    return render_template('destinations/add_destination.html',
                           title='Add Destination',
                           form=form)


@bp.route('/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def edit(id):
    def flash_errors(form):
        for field, errors in form.errors.items():
            for error in errors:
                flash(u"Error in the %s field - %s" % (
                    getattr(form, field).label.text,
                    error
                ))

    d = Destination.query.get(id)

    if request.method == 'POST':  # image upload
        form = EditDestinationForm()
        if form.validate_on_submit():
            if save_destination(form, d, new=False):
                flash('Destination "{}" edited!'.format(str(form.title.data)))
                return redirect(url_for('main.index'))
        else:
            flash_errors(form)
            flash('ERROR! Destination was not edited.', 'error')
            return redirect(url_for('main.index', id=d.id))

    # BELOW FOR PREPOPULATING FORM

    routes = d.routes.first()
    additional_photos = d.additional_photos.all()
    cost = d.cost.first()
    months = d.months.first()
    accomodation = d.accomodation.first()
    approach = d.approach.first()
    car = d.car.first()

    # Country
    d.country_code = pycountry_convert.country_name_to_country_alpha2(d.country)

    # additional_photos
    d.addit_photos = additional_photos

    # routes
    d.main_discipline = routes.main_discipline
    d.traditional = routes.traditional
    d.sport = routes.sport
    d.bouldering = routes.bouldering
    d.total_routes = routes.total_routes
    d.total_sport = routes.total_sport
    d.total_trad = routes.total_trad
    d.total_boulders = routes.total_boulders
    d.easy_routes = routes.easy_routes
    d.intermediate_routes = routes.intermediate_routes
    d.hard_routes = routes.hard_routes
    d.very_hard_routes = routes.very_hard_routes

    # cost
    d.cost_form_currency = cost.cost_form_currency
    d.beer_at_establishment = cost.beer_at_establishment
    d.coffee_at_establishment = cost.coffee_at_establishment
    d.restaurant_inexpensive_meal = cost.restaurant_inexpensive_meal
    d.groceries_one_week = cost.groceries_one_week
    d.car_rent_one_week = cost.car_rent_one_week
    d.gas_one_liter = cost.gas_one_liter
    d.km_per_day = cost.km_per_day
    d.tent_per_day = cost.tent_per_day
    d.van_per_day = cost.van_per_day
    d.camping_per_day = cost.camping_per_day
    d.hostel_per_day = cost.hostel_per_day
    d.apartment_per_day = cost.apartment_per_day
    d.house_per_day = cost.house_per_day
    d.hotel_per_day = cost.hotel_per_day

    # months
    d.january = months.january
    d.february = months.february
    d.march = months.march
    d.april = months.april
    d.may = months.may
    d.june = months.june
    d.july = months.july
    d.august = months.august
    d.september = months.september
    d.october = months.october
    d.november = months.november
    d.december = months.december

    # accomodation
    d.tent = accomodation.tent
    d.van = accomodation.van
    d.hostel = accomodation.hostel
    d.camping = accomodation.camping
    d.apartment = accomodation.apartment
    d.house = accomodation.house
    d.hotel = accomodation.hotel

    # approach
    d.easy = approach.easy
    d.moderate = approach.moderate
    d.hardcore = approach.hardcore

    # car
    d.not_needed = car.not_needed
    d.good_to_have = car.good_to_have
    d.must_have = car.must_have

    form = EditDestinationForm(obj=d)

    return render_template('destinations/edit_destination.html',
                           title='Edit Destination',
                           form=form,
                           destination=d)


@bp.route('/<int:id>/delete')
@login_required
def delete(id):
    d = Destination.query.get(id)
    db.session.delete(d)
    db.session.commit()
    flash('Destination "{}" deleted!'.format(d.title))
    return redirect(url_for('main.index'))

@bp.route('/<int:id>/additional_photo/<int:photo_id>/delete')
@login_required
def delete_additional_img(id, photo_id):
    photo = AdditionalPhotos.query.get(photo_id)
    db.session.delete(photo)
    db.session.commit()
    flash('Additional image deleted!')
    return redirect(url_for('main.index'))

app/templates/destinations/edit_destination.html
{% extends "base.html" %}

{% block content %}
<script>
    var editDestinationFormFuctionality = {

        onReady: function () {

            $('select#country option').first().attr('disabled', true)

            $('select#country option[value={{ destination.country_code }}]').attr('selected', 'selected')
        
        }

    }

    $(document).ready(editDestinationFormFuctionality.onReady)
</script>

<div class="add-destination-container">
    <h1>{{ title }}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <h3><span>*</span> {{ form.title.label }}</h3>
        {{ form.title(size=64) }}<br>
        {% for error in form.title.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}


        <h3><span class="required">*</span> {{ form.country.label }}</h3>
        {{ form.country() }}
        {% for error in form.country.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}

        <h3><span>*</span> {{ form.weather_place_autocomplete.label }}</h3>
        <p>Start writing, then select from list.</p>
        {{ form.weather_place_autocomplete }} <br>

        <h3><span>*</span> {{ form.featured_photo.label }}</h3>
        <p>Please only use a landscape oriented photo here, it will look much better (jpg/jpeg)</p>
        {{ form.featured_photo }} <br>
        {% for error in form.featured_photo.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}

        <h3>{{ form.additional_photos.label }} </h3>
        <p>Any aspect ratio is fine here (jpg/jpeg)</p>
        {{ form.additional_photos }} <br>
        {% for error in form.additional_photos.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
        
        {% for photo in destination.addit_photos %}
            <img width="150px" src="{{ destination.photo_folder_url  }}additional_photos/{{ photo.additional_photo_filename }}-thumbnail.{{ photo.additional_photo_extension }}" alt="">
            <a href="{{ url_for('destinations.delete_additional_img', id=destination.id, photo_id=photo.id) }}">Delete</a>
        {% endfor %}

        <h3>{{ form.description.label }}</h3>
        <p>Describe the area, it's history, access/travel info, accomodation, weather characteristics, route characteristics, topos/books, things that are good to know, etc.</p>
        {{ form.description }}

        <h3>{{ form.main_discipline.label }} </h3>
        <div id="discipline_buttons_wrap">{{ form.main_discipline }}</div>

        <h4>Also has these</h4>
        <ul class="list-discipline">
            <li>{{ form.traditional }} {{ form.traditional.label }}</li>
            <li>{{ form.sport }} {{ form.sport.label }}</li>
            <li>{{ form.bouldering }} {{ form.bouldering.label }}</li>
        </ul>
        </ul>
        {% for error in form.main_discipline.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}


        <h3>Months in season</h3>
        <ul>
            <li>{{ form.january }} {{ form.january.label }}</li>
            <li>{{ form.february }} {{ form.february.label }}</li>
            <li>{{ form.march }} {{ form.march.label }}</li>
            <li>{{ form.april }} {{ form.april.label }}</li>
            <li>{{ form.may }} {{ form.may.label }}</li>
            <li>{{ form.june }} {{ form.june.label }}</li>
            <li>{{ form.july }} {{ form.july.label }}</li>
            <li>{{ form.august }} {{ form.august.label }}</li>
            <li>{{ form.september }} {{ form.september.label }}</li>
            <li>{{ form.october }} {{ form.october.label }}</li>
            <li>{{ form.november }} {{ form.november.label }}</li>
            <li>{{ form.december }} {{ form.december.label }}</li>
        </ul>

        <h3>Accomodations available</h3>
        <ul>
            <li>{{ form.tent }} {{ form.tent.label }}</li>
            <li>{{ form.van }} {{ form.van.label }}</li>
            <li>{{ form.camping }} {{ form.camping.label }}</li>
            <li>{{ form.hostel }} {{ form.hostel.label }}</li>
            <li>{{ form.apartment }} {{ form.apartment.label }}</li>
            <li>{{ form.house }} {{ form.house.label }}</li>
            <li>{{ form.hotel }} {{ form.hotel.label }}</li>
        </ul>

        <h3>Approach:</h3>
        <ul>
            <li>{{ form.easy }} {{ form.easy.label }}</li>
            <li> {{ form.moderate }} {{ form.moderate.label }}</li>
            <li>{{ form.hardcore }} {{ form.hardcore.label }}</li>
        </ul>

        <h3>Car</h3>
        <ul>
            <li>{{ form.not_needed }} {{ form.not_needed.label }}</li>
            <li>{{ form.good_to_have }} {{ form.good_to_have.label }}</li>
            <li>{{ form.must_have }} {{ form.must_have.label }}</li>
        </ul>

        <h2>Cost and prices for this destination</h2>
        <p>Please fill in as much as you can. Only use numbers and dots (3.14 is correct). Do not use comma (3,14 is wrong).</p>

        <h3>{{ form.cost_form_currency.label }}</h4>
        <p>Just select the currency you will use to enter the prices. Does not have to be the local currency.</p>
        {{ form.cost_form_currency }}

        <h3>Food and drinks</h3>
        <p>For beer, coffee and restaurant prices, see <a href="https://www.numbeo.com/cost-of-living/">Cost of Living index (Numbeo)</a>. For one days worth of groceries, see <a href="https://www.numbeo.com/food-prices/">Food prices index (Numbeo)</a></p>
      
        <h4><span class="required">*</span> {{ form.beer_at_establishment.label }}</h4>
        {{ form.beer_at_establishment }} <span class="cost-field-currency">EUR</span>
    
        <h4><span class="required">*</span> {{ form.coffee_at_establishment.label }}</h4>
        {{ form.coffee_at_establishment }} <span class="cost-field-currency">EUR</span>
    
        <h4><span class="required">*</span> {{ form.restaurant_inexpensive_meal.label }}</h4>
        {{ form.restaurant_inexpensive_meal }} <span class="cost-field-currency">EUR</span>
    
        <h4><span class="required">*</span> {{ form.groceries_one_week.label }}</h4>
        {{ form.groceries_one_week }} <span class="cost-field-currency">EUR</span>
         

        <h3>Car</h3>
        <p>For one week rental prices, see <a href="https://www.rentalcars.com/">Rental Cars</a>, <a
                href="https://www.avis.com/en/locations/avisworldwide">Avis</a>, <a
                href="https://www.hertz.no/rentacar/location">Hertz</a> or <a
                href="https://www.sixt.com/car-rental/">SiXT</a>. For gas prices, see <a href="https://www.numbeo.com/gas-prices/">Gas prices index (Numbeo)</a>.</p>
        
        <h4>{{ form.car_rent_one_week.label }}</h4>
        {{ form.car_rent_one_week }} <span class="cost-field-currency">EUR</span>
        
        <h4>{{ form.gas_one_liter.label }}</h4>
        {{ form.gas_one_liter }} <span class="cost-field-currency">EUR</span>
        
        <h4>{{ form.km_per_day.label }}</h4>
        {{ form.km_per_day }} <span style="color:#ccc">km</span>
        

        <h3>Accomodation</h3>
        <p>Just leave the unavailable accomodations blank. </p>
            <h4>{{ form.tent_per_day.label }}</h4>
            {{ form.tent_per_day }} <span class="cost-field-currency">EUR</span>
        
            <h4>{{ form.van_per_day.label }}</h4>
            {{ form.van_per_day }} <span class="cost-field-currency">EUR</span>

            <h4>{{ form.camping_per_day.label }}</h4>
            {{ form.camping_per_day }} <span class="cost-field-currency">EUR</span>

            <h4>{{ form.hostel_per_day.label }}</h4>
            {{ form.hostel_per_day }} <span class="cost-field-currency">EUR</span>

            <h4>{{ form.apartment_per_day.label }}</h4>
            {{ form.apartment_per_day }} <span class="cost-field-currency">EUR</span>

            <h4>{{ form.house_per_day.label }}</h4>
            {{ form.house_per_day }} <span class="cost-field-currency">EUR</span>

            <h4>{{ form.hotel_per_day.label }}</h4>
            {{ form.hotel_per_day }} <span class="cost-field-currency">EUR</span>


        <h2>Routes information</h2>
        <p>Please fill in as much as you can. Only use numbers and dots (3.14 is correct). Do not use comma (3,14 is wrong).</p>

        <h4>{{ form.total_routes.label }}</h4>
        {{ form.total_routes }}

        <h4>{{ form.total_sport.label }}</h4>
        {{ form.total_sport }}

        <h4>{{ form.total_trad.label }}</h4>
        {{ form.total_trad }}

        <h4>{{ form.total_boulders.label }}</h4>
        {{ form.total_boulders }}
        
        <br><br><br><br>
        
        <img width="500px" src="{{ url_for('static', filename='images/grades_categorization.png') }}" alt="">
        <br>
        <p>
            <strong><u>The following four fields are used to create the staple diagram for this destination.</u></strong>
            If you don't know the number of routes, just put in percentage numbers (but without '%'),
            e.g. easy: 0.25, intermediate: 0.45, hard: 0.2, very hard: 0.1.
        </p>
        <p>Use the table above for reference.</p>

        <h4><span class="easy-routes">{{ form.easy_routes.label }}</span></h4>
        {{ form.easy_routes }}

        <h4><span class="intermediate-routes">{{ form.intermediate_routes.label }}</span></h4>
        {{ form.intermediate_routes }}

        <h4><span class="hard-routes">{{ form.hard_routes.label }}</span></h4>
        {{ form.hard_routes }}

        <h4><span class="very-hard-routes">{{ form.very_hard_routes.label }}</span></h4>
        {{ form.very_hard_routes }}

        <h2 style="text-align: center;">Thank you so much! :)</h2>

        {{ form.submit() }}
    </form>
</div>

<script>

    var autocomplete, place;

    var options = {
        types: ['geocode']
    };

    function initAutocomplete() {
        // Create the autocomplete object, restricting the search predictions to
        // geographical location types.
        autocomplete = new google.maps.places.Autocomplete(
            document.getElementById('weather_place_autocomplete'), options);

        // Avoid paying for data that you don't need by restricting the set of
        // place fields that are returned to just the address components.
        autocomplete.setFields(['geometry']);

        // When the user selects an address from the drop-down, populate the
        // address fields in the form.
        autocomplete.addListener('place_changed', fillInLatitudeLongitude);

        // Add a DOM event listener to react when the user selects a country.
        document.getElementById('country').addEventListener(
            'change', setAutocompleteCountry);
    }

    // Set the country restriction based on user input.
    // Also center and zoom the map on the given country.
    function setAutocompleteCountry() {
        var country = document.getElementById('country').value;
        if (country === 'all') {
            autocomplete.setComponentRestrictions({ 'country': [] });
        } else {
            autocomplete.setComponentRestrictions({ 'country': country });
        }
    }

    function fillInLatitudeLongitude() {
        // Get the place details from the autocomplete object.
        place = autocomplete.getPlace();

        document.getElementById('weather_ltd').value = place.geometry.location.lat();
        document.getElementById('weather_lng').value = place.geometry.location.lng();

        console.log(document.getElementById('weather_ltd').value)
        console.log(document.getElementById('weather_lng').value)

    }

</script>
<script>
    $('#description').summernote({
        minHeight: 200,
        toolbar: [
            // [groupName, [list of button]]
            ['style', ['bold', 'italic', 'underline', 'clear', 'H1']],
            ['font', ['strikethrough', 'superscript', 'subscript']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['picture'],
            ['link'],
            ['table']
        ],
        placeholder: 'Write here...'
    });
</script>
<script>
var currencyFormChange = {
    
    onReady: function () {
        $('select#cost_form_currency').change(function () {
            console.log("hasd")
            $('span.cost-field-currency').text($(this).val()) 
        })
    }

}
$(document).ready(currencyFormChange.onReady)
</script>
<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8XiZomiVMq2KmbTlj6OPu6tILBrkTYoQ&libraries=places&callback=initAutocomplete"
    async defer></script>

{% endblock %}

app/templates/destinations/suggest_update.html
{% extends "base.html" %}

{% block content %}

<script>
    var editDestinationFormFuctionality = {
        onReady: function () {
            $('select#destination_title option').first().attr('disabled', true)
            $('select#destination_title option[value={{ destination.title }}]').attr('selected', 'selected')
        }
    }

    $(document).ready(editDestinationFormFuctionality.onReady)
</script>

<div class="content-container">
    <div class="radius-shadow-window"> 
        <h1>{{ title }}</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {{ form.hidden_tag() }}

            <h3><span class="required">*</span> {{ form.subject.label }}</h3>
            {{ form.subject(size=64) }}<br>
            {% for error in form.subject.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}

            <h3><span class="required">*</span> {{ form.destination_title.label }}</h3>
            {{ form.destination_title() }}<br>
            {% for error in form.destination_title.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}

            <h3><span class="required">*</span> {{ form.sender_email.label }}</h3>
            {{ form.sender_email() }}<br>
            {% for error in form.sender_email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}

            <h3><span class="required">*</span> {{ form.message.label }}</h3>
            {{ form.message(class_="general-form-textarea") }}<br>
            {% for error in form.message.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
            <br>
            {{ form.submit(class_='button') }}
            <h2 style="text-align: center;">Thank you! :)</h2>
        </form>
    </div>
</div>

{% endblock %}